POST http://localhost:3000/institutions/
Content-Type: application/json

{
    "institutionName": "Emilly Mayara INDIO-ONG",
    "urlImage" : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdgHjPfPR117BEONZf9EfO2Oi9x2zBLiW-Dw&s"
}

###SDHAUKDGAKDH
GET http://localhost:3000/institutions

###
DELETE http://localhost:3000/institutions/inst_eOgZx-VAf_YbnIDJCiC-6