POST http://localhost:3000/donations/
Content-Type: application/json

{
    "donatorName": "Emilly Mayara de Brito Santos",
    "amount": 450,
    "date": "2025-10-04",
    "donatorCpf": "123.456.789-10",
    "donatorPhone": "99999-9999",
    "typePayment": "Pix",
    "institutionId": "inst_VFVs6Ftn7dklAIsUeW5tn"
}

###SDHAUKDGAKDH
GET http://localhost:3000/donations

###

DELETE http://localhost:3000/donations/dev_ptTQrn0j0oq3aTjKrj-E4
